### PR TITLE
Fix up non-ideal state styling

### LINKED ISSUE #50: Error messages are malformed when displayed to users
image

@lediur Let's talk through how we want to surface error messages to users. The above is a bit raw more my liking, but I understand the prototype nature of what we currently have shipped.

### PR DESCRIPTION
**Pull request by lediur**
image

Resolves #50

### CODE REVIEW

File: src/content/headsup/NonIdealHeadsup.tsx [hunk 1]
```diff
@@ -83,31 +89,50 @@ export class ErrorHeadsUp extends React.PureComponent<
...
+      >
+        <div className="error-briefing">
+          <div className="error-briefing-message">
+            <Icon
+              icon={IconNames.WARNING_SIGN}
+              className="error-icon"
+              intent={Intent.DANGER}
+            />
+            <div className="error-message-text">
+              Couldn't load Preflight. Make sure <code>api.secarta.io</code> is
```
Comment (dlukeomalley) [inline src/content/headsup/NonIdealHeadsup.tsx]: "Couldn't load Preflight. Is api.secarta.io blocked by your browser?"
