### PR TITLE
Address #133, gracefully fail

### LINKED ISSUE #133: Overly sensitive conditional for error state triggers on dojo/dojo
Navigated to https://github.com/dojo/dojo, greeted with an error message for Preflight:

image

Caused by us triggering error state if `findings/` returns 404. We should degrade more gracefully as there is still useful information for us to surface.

### PR DESCRIPTION
**Pull request by dlukeomalley**
## Before

image

## After

image

Fixes #133

### CODE REVIEW

File: src/content/headsup/index.tsx [hunk 1]
```diff
@@ -66,13 +68,15 @@ class NormalHeadsUp extends React.PureComponent<HeadsUpProps, HeadsupState> {
...
+                    {data.pkg && <UsedBy pkg={data.pkg} />}
                   </div>
                 </div>
               </div>
-            )}
-          </>
-        )}
+            );
+          } else {
+            return <ErrorHeadsUp error={new Error("")} />;
```
Comment (dlukeomalley) [inline src/content/headsup/index.tsx]:
```suggestion
            return <ErrorHeadsUp error={new Error("Something went wrong! We're unable to determine the reason.")} />;
```

File: src/content/headsup/index.tsx [hunk 2]
```diff
@@ -33,24 +33,26 @@ class NormalHeadsUp extends React.PureComponent<HeadsUpProps, HeadsupState> {
...
-              )}
-            {data && (
+        {({ loading, error, data, response }) => {
+          if (loading) {
+            return <LoadingHeadsUp />;
+          } else if (response != null && response.repo.status === 404) {
+            return <UnsupportedHeadsUp />;
+          } else if (
+            error &&
+            (response == null || response.repo.status !== 404)
```
Comment (lediur) [inline src/content/headsup/index.tsx]:
```suggestion
            (response == null || response.repo.status !== 404) // Failed to make a network request or received a non-404 failure status code
```
